### ISSUE TITLE
How to use this repo?

### ISSUE THREAD

**Issue by Deleora** [k0derAl/whatsAppUnDelete#1]
How exactly can I use this repo? Is it going to be a modded client of Whatsapp?

**Comment by k0derAl** [comment]
Hello
My app listern push notification.

**Comment by Deleora** [comment]
Hi,
Is the project complete or still under development?

**Comment by k0derAl** [comment]
under development

**Comment by Deleora** [comment]
Alright, seems interesting. Good luck!!
